# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12user_service.proto\x12\x04user\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"<\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"&\n\x13ValidateUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"E\n\x14ValidateUserResponse\x12\x0e\n\x06\x65xists\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t2\x89\x01\n\x0bUserService\x12\x33\n\x07GetUser\x12\x14.user.GetUserRequest\x1a\x12.user.UserResponse\x12\x45\n\x0cValidateUser\x12\x19.user.ValidateUserRequest\x1a\x1a.user.ValidateUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'user_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_GETUSERREQUEST']._serialized_start=28
  _globals['_GETUSERREQUEST']._serialized_end=61
  _globals['_USERRESPONSE']._serialized_start=63
  _globals['_USERRESPONSE']._serialized_end=123
  _globals['_VALIDATEUSERREQUEST']._serialized_start=125
  _globals['_VALIDATEUSERREQUEST']._serialized_end=163
  _globals['_VALIDATEUSERRESPONSE']._serialized_start=165
  _globals['_VALIDATEUSERRESPONSE']._serialized_end=234
  _globals['_USERSERVICE']._serialized_start=237
  _globals['_USERSERVICE']._serialized_end=374
# @@protoc_insertion_point(module_scope)
